### ISSUE TITLE
ValueError: Improper config format:

### ISSUE THREAD

**Issue by CColten** [xiaochus/Vehicle_Tracking#1]
thanks for the program !
when I run the program，the error appeared in model = load_model('model/weights.h5) like this:
ValueError: Improper config format: {u'l2': 0.0005000000237487257, u'name': u'L1L2Regularizer', u'l1': 0.0}

i'm working in Python 2.7,  do you know the reason .

**Comment by xiaochus** [comment]
This program is based on python 3.6 and keras 1.2.2. If you are using keras 2, the structure of the saved model file will be different and causing an error when loading h5 model.

You can change the keras version or re-train the cnn model.

**Comment by xiaochus** [comment]
@CColten 
This program is based on python 3.6 and keras 1.2.2. If you are using keras 2, the structure of the saved model file will be different and causing an error when loading h5 model.

You can change the keras version or re-train the cnn model.

**Comment by CColten** [comment]
thank you for your reply. the problem is what you said
